/**
 * Mock SEC filing summaries for the landing hero Gmail demo widget.
 * Extracted from gmail-inbox-hero.tsx per /review_plan §1 Issue 2.
 * Pure data — no side effects, no JSX, no state.
 *
 * Note: `icon` references Lucide React components, imported here
 * so the data file is self-contained.
 */

import {
  AlertTriangle,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Users,
  FileText,
  Zap,
} from 'lucide-react';

export interface FinancialHighlight {
  metric: string;
  value: string;
  change: string;
}

export interface EmailSummary {
  id: number;
  ticker: string;
  companyName: string;
  filingType: string;
  filedAt: string;
  timeAgo: string;
  headline: string;
  preview: string;
  summaryText: string;
  keyTakeaway: string;
  investorImpact: string;
  sentiment: 'bullish' | 'bearish' | 'neutral';
  importance: 'critical' | 'high' | 'medium' | 'low';
  icon: React.ComponentType<{ className?: string }>;
  isStarred: boolean;
  financialHighlights: FinancialHighlight[];
}

/**
 * Curated real summaries from the database
 * Ranked by significance and impact to investor sentiment
 * Verified against news sources for quality
 */
export const curatedSummaries: EmailSummary[] = [
  {
    id: 1,
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    filingType: 'DEFA14A',
    filedAt: 'Oct 28, 2025',
    timeAgo: '2 hours ago',
    headline: "Tesla urges $1tn Musk pay vote\u2014'high odds' he quits without it",
    preview: "Board Chair Robyn Denholm tours NYC institutions, counters ISS/Glass Lewis 'no' recs. Nov 6 vote locks Musk's 25% control for AI safety.",
    summaryText: "Tesla blasts letters, interviews, and X posts urging yes vote on Musk's $1tn pay package by Nov 6\u2014Denholm admits high odds Musk quits without it, eyeing internal successors like Tom Zhu. Board Chair Robyn Denholm tours NYC institutions, counters ISS/Glass Lewis 'no' recs, stresses package delivers Musk 25% voting control first (economic rights lag 7.5-10 years) to safeguard AI/robot armies\u2014not cash grab.",
    keyTakeaway: "Nov 6 vote locks Musk's 25% control for AI safety, or Tesla risks CEO walkout\u2014no named Plan B beyond internals.",
    investorImpact: "Pass secures Musk's focus on $8.5tn vision; fail sparks leadership chaos, stock plunge.",
    sentiment: 'bullish',
    importance: 'critical',
    icon: AlertTriangle,
    isStarred: true,
    financialHighlights: [
      { metric: 'Pay Package', value: '$1tn', change: '+12 tranches' },
      { metric: 'Market Cap Target', value: '$8.5tn', change: '6x current' },
      { metric: 'EBITDA Milestone', value: '$50B-$400B', change: '3x highest' },
    ],
  },
  {
    id: 2,
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    filingType: 'FWP',
    filedAt: 'Nov 4, 2025',
    timeAgo: '4 hours ago',
    headline: 'Alphabet raises $17.5B in bonds for AI expansion',
    preview: "Seven tranches spanning 2028-2075 at sub-6% yields. Biggest $4B 2055s at 5.450% coupon\u2014tight spreads signal strong demand.",
    summaryText: "Alphabet priced $17.5B in senior notes across seven tranches plus floaters, biggest $4B 2055s at 5.450% coupon yielding 5.495% (T+82bps). Company locks in cheap debt now\u2014yields climb from 3.905% on 2028s to 5.745% on 2075s\u2014net proceeds top $17.4B before expenses, funding AI capex or buybacks without dilution.",
    keyTakeaway: "Alphabet grabs $17.5B at peak-tight spreads (T+30-107bps), fueling balance sheet for capex without share dilution.",
    investorImpact: "Cheap long-dated debt (up to 2075s under 6% YTM) enhances flexibility, pure bull signal for equity holders.",
    sentiment: 'bullish',
    importance: 'high',
    icon: TrendingUp,
    isStarred: true,
    financialHighlights: [
      { metric: 'Total Raised', value: '$17.5B', change: '+7 tranches' },
      { metric: 'Longest Maturity', value: '2075', change: '50 years' },
      { metric: 'Spread Range', value: 'T+30-107bps', change: 'Tight' },
    ],
  },
  {
    id: 3,
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    filingType: 'Form 4',
    filedAt: 'Oct 29, 2025',
    timeAgo: '6 hours ago',
    headline: "Jensen Huang sells $23.56M\u2014routine 10b5-1, not a bailout",
    preview: "CEO sold 125,000 shares via pre-planned sale. Direct holdings at 69.7M shares, pocket change against 782M indirect in trusts.",
    summaryText: "NVIDIA CEO Jen-Hsun Huang sold 125,000 shares for $23.56M at $184.24-$202.64/share Oct 24-28 via March 2025 10b5-1 plan. Direct holdings dropped to 69,758,203 from 69,883,203\u2014a 0.18% trim, pocket change against 782M indirect shares in trusts/LLCs. Routine auto-sell into strength, not a bailout\u2014insiders diversify mechanically.",
    keyTakeaway: "Programmed 10b5-1 sale cashed $23.56M without signaling doubt\u2014standard for execs sitting on billions.",
    investorImpact: "Negligible direct stake dip via autopilot plan; bullish context intact, no reason to flinch.",
    sentiment: 'neutral',
    importance: 'medium',
    icon: DollarSign,
    isStarred: false,
    financialHighlights: [
      { metric: 'Shares Sold', value: '125,000', change: '-0.18%' },
      { metric: 'Sale Proceeds', value: '$23.56M', change: '10b5-1' },
      { metric: 'Indirect Holdings', value: '782M', change: 'Unchanged' },
    ],
  },
  {
    id: 4,
    ticker: 'CMG',
    companyName: 'Chipotle Mexican Grill',
    filingType: '10-Q',
    filedAt: 'Oct 29, 2025',
    timeAgo: '8 hours ago',
    headline: 'Q3 revenue +7.5% to $3B but traffic woes persist',
    preview: "Comp sales eked out 0.3% on 1.1% higher checks offset by 0.8% transaction drop. Buybacks slashed shares 2.5% YTD.",
    summaryText: "Chipotle's Q3 revenue surged 7.5% to $3.00B, but comp sales eked out just 0.3% on 1.1% higher checks offset by 0.8% transaction drop\u2014traffic woes persist. Restaurant-level margins held firm at 25.2% despite wage hikes, thanks to prior menu pricing, while G&A jumped 15.9% to $147M on retention bonuses post-CEO exit.",
    keyTakeaway: "Buybacks slashed shares 2.5% YTD to 1.325B outstanding, juicing EPS despite traffic slump\u2014$652M auth remains for more.",
    investorImpact: "Unit growth and buybacks bolster EPS growth thesis, but persistent traffic weakness signals pricing power erosion amid macro pressures.",
    sentiment: 'bearish',
    importance: 'high',
    icon: TrendingDown,
    isStarred: false,
    financialHighlights: [
      { metric: 'Revenue Q3', value: '$3.00B', change: '+7.5% YoY' },
      { metric: 'Comp Sales', value: '+0.3%', change: 'Traffic -0.8%' },
      { metric: 'EPS Q3', value: '$0.29', change: '+3.6%' },
    ],
  },
  {
    id: 5,
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    filingType: 'FWP',
    filedAt: 'Nov 3, 2025',
    timeAgo: '12 hours ago',
    headline: 'Alphabet locks in \u20AC6.5B in Euro notes at tight spreads',
    preview: "Six tranches spanning 2028-2064, yields from 2.476% to 4.474%. Net proceeds \u20AC6.417B for AI capex and debt paydown.",
    summaryText: "Alphabet priced \u20AC6.5B in Euro-denominated senior notes spanning 2028-2064, locking in yields from 2.476% (2028s) to 4.474% (2064s)\u2014tight spreads like +25bps to mid-swaps on short end signal strong demand. Net proceeds hit \u20AC6.417B after skimpy underwriting cuts (0.15%-0.60%), earmarked for general corporate uses including debt paydown.",
    keyTakeaway: "\u20AC6.5B raised at sub-4.5% yields to 2064 locks ultra-cheap debt for capex/buybacks\u2014no dilution red flag.",
    investorImpact: "Bullish signal: pristine pricing reflects GOOGL's funding edge, fuels growth without share pressure.",
    sentiment: 'bullish',
    importance: 'high',
    icon: TrendingUp,
    isStarred: false,
    financialHighlights: [
      { metric: 'Total Raised', value: '\u20AC6.5B', change: '6 tranches' },
      { metric: 'Yield Range', value: '2.5%-4.5%', change: 'Sub-market' },
      { metric: 'Net Proceeds', value: '\u20AC6.417B', change: 'AI capex' },
    ],
  },
  {
    id: 6,
    ticker: 'VRT',
    companyName: 'Vertiv Holdings Co',
    filingType: '10-Q',
    filedAt: 'Nov 3, 2025',
    timeAgo: '1 day ago',
    headline: 'Organic orders surge 60% on AI data center demand',
    preview: "Q3 revenue up 29% to $2.68B, backlog swells to $9.5B. Caterpillar partnership expands power and cooling offerings.",
    summaryText: "Vertiv reported Q3 net sales of $2,676M, up 29% YoY driven by 43% Americas growth. Organic orders surged 60% YoY, with book-to-bill ratio of 1.4x and backlog at $9.5B. New OCP-compliant rack solutions support 142kW loads for AI infrastructure.",
    keyTakeaway: "AI infrastructure pure-play sees 60% order growth, 29% revenue jump\u2014backlog at $9.5B signals sustained demand.",
    investorImpact: "Clear winner from AI data center buildout. Caterpillar partnership and liquid cooling demand accelerate.",
    sentiment: 'bullish',
    importance: 'high',
    icon: Zap,
    isStarred: true,
    financialHighlights: [
      { metric: 'Revenue Q3', value: '$2.68B', change: '+29% YoY' },
      { metric: 'Organic Orders', value: '+60%', change: 'YoY' },
      { metric: 'Backlog', value: '$9.5B', change: '1.4x B2B' },
    ],
  },
  {
    id: 7,
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    filingType: 'DEFA14A',
    filedAt: 'Nov 4, 2025',
    timeAgo: '1 day ago',
    headline: 'Counterpoint Global votes FOR Musk comp plan',
    preview: "Morgan Stanley's active investor endorses skin-in-game leadership. Cites Musk's irreplaceable role in mobility, energy, robotics.",
    summaryText: "Tesla unleashes Musk, Gebbia, and Taneja on X November 3-4 to rally votes for Musk's performance-based comp plan at 2025 AGM. Counterpoint Global (Morgan Stanley) piles on, voting FOR the plan because Musk delivers culture, returns, and upside in mobility, energy, robotics; wants his 'skin in the game.'",
    keyTakeaway: "Counterpoint Global's public FOR vote bolsters Musk comp approval odds, signaling institutional buy-in on skin-in-game leadership.",
    investorImpact: "Ramps proxy win probability, locking Musk to Tesla milestones\u2014bullish for alignment if passed.",
    sentiment: 'bullish',
    importance: 'medium',
    icon: Users,
    isStarred: false,
    financialHighlights: [
      { metric: 'Endorsement', value: 'FOR', change: 'Counterpoint' },
      { metric: 'Rationale', value: 'Skin-in-game', change: 'Leadership' },
      { metric: 'Vote Date', value: 'Nov 6', change: '2 days' },
    ],
  },
  {
    id: 8,
    ticker: 'KO',
    companyName: 'Coca-Cola Co',
    filingType: 'Form 4',
    filedAt: 'Oct 31, 2025',
    timeAgo: '2 days ago',
    headline: 'CFO gifts 33k shares to kids\u2014trust dissolved',
    preview: "Murphy shifted 74,400 more to direct holdings now at 279,911 shares. Estate planning, not a sale\u2014price $0, code G.",
    summaryText: "KO CFO John Murphy gifted 33,000 shares to his kids on 10/29/2025 via trust termination, shifting 74,400 more to his direct holdings now at 279,911 shares. Trust dissolved completely\u2014no indirect shares left there\u2014while wife holds 2,407 and his 401(k) has 1,027. Not a sale (price $0, code G), just estate planning.",
    keyTakeaway: "Murphy gifted 33k shares to kids, not sold\u2014neutral estate move, no cash exit.",
    investorImpact: "Bearish if pattern emerges, but single gift signals routine planning over panic.",
    sentiment: 'neutral',
    importance: 'low',
    icon: Users,
    isStarred: false,
    financialHighlights: [
      { metric: 'Shares Gifted', value: '33,000', change: 'To children' },
      { metric: 'Direct Holdings', value: '279,911', change: '+74,400' },
      { metric: 'Transaction Type', value: 'Gift', change: 'No proceeds' },
    ],
  },
  {
    id: 9,
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    filingType: '144',
    filedAt: 'Oct 29, 2025',
    timeAgo: '2 days ago',
    headline: "Huang's 4.1M-share 3-month sell-off continues",
    preview: "CEO plans to sell 25,000 more shares ($5.2M). 56 transactions since July under pre-planned 10b5-1\u2014routine diversification.",
    summaryText: "NVIDIA CEO Jensen Huang plans to sell 25,000 shares ($5.2M at $207.91/share) on 10/29/2025 via Charles Schwab. This caps a 3-month sell-off where he dumped 4.1M shares across 56 transactions\u201454 lots of 75,000 shares plus two 25,000-share trades from 7/29 to 10/28.",
    keyTakeaway: "Huang's 4.1M-share 3-month sell-off plus $5.2M more is standard 10b5-1 housekeeping for a billionaire CEO, not a red flag.",
    investorImpact: "Negligible supply hit from planned insider sales; ignore unless volume spikes off-plan.",
    sentiment: 'neutral',
    importance: 'low',
    icon: DollarSign,
    isStarred: false,
    financialHighlights: [
      { metric: 'Planned Sale', value: '25,000', change: '$5.2M' },
      { metric: '3-Month Total', value: '4.1M', change: '56 trades' },
      { metric: 'Outstanding %', value: '0.017%', change: 'Negligible' },
    ],
  },
  {
    id: 10,
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    filingType: 'Form 4',
    filedAt: 'Nov 4, 2025',
    timeAgo: '3 days ago',
    headline: 'CEO Sundar Pichai sells $8.1M in stock',
    preview: "Sales executed at $247-$252 near 52-week high. Rule 10b5-1 plan from Dec 2024\u2014now holds 2.37M Class C shares.",
    summaryText: "Alphabet CEO Sundar Pichai sold $8.13M worth of Class C stock on October 15 in multiple transactions at $247-$252, near the 52-week high of $256.96. Sales under Rule 10b5-1 plan adopted December 2024. Directly owns 2,369,619 Class C shares post-sale.",
    keyTakeaway: "Pre-planned 10b5-1 sale by CEO near highs\u2014standard diversification, not a warning sign.",
    investorImpact: "Routine insider sale under preset plan; GOOGL's AI momentum and bond raise overshadow noise.",
    sentiment: 'neutral',
    importance: 'low',
    icon: DollarSign,
    isStarred: false,
    financialHighlights: [
      { metric: 'Sale Amount', value: '$8.1M', change: '10b5-1' },
      { metric: 'Sale Price', value: '$247-$252', change: 'Near ATH' },
      { metric: 'Holdings Post', value: '2.37M', change: 'Class C' },
    ],
  },
  {
    id: 11,
    ticker: 'CMG',
    companyName: 'Chipotle Mexican Grill',
    filingType: '8-K',
    filedAt: 'Oct 29, 2025',
    timeAgo: '3 days ago',
    headline: 'Q3 earnings announced\u2014check Exhibit 99.1',
    preview: "Pure announcement play. Conference call at 4:30pm ET. Actual numbers in press release attachment.",
    summaryText: "Chipotle announced Q3 earnings (ended Sep 30, 2025) via press release on Oct 29\u2014no numbers in the 8-K, check Exhibit 99.1. Management hosts conference call at 4:30pm ET today to dissect results. Boilerplate filing signals fresh data dump, but devil's in the unattached press release.",
    keyTakeaway: "Pure announcement play\u2014grab the press release for actual Q3 numbers, this 8-K is just the wrapper.",
    investorImpact: "Neutral filing until press release digest; sets stage for call but reveals zero meat.",
    sentiment: 'neutral',
    importance: 'low',
    icon: FileText,
    isStarred: false,
    financialHighlights: [
      { metric: 'Period', value: 'Q3 FY25', change: 'Sep 30' },
      { metric: 'Details', value: 'Exhibit 99.1', change: 'Press release' },
      { metric: 'Call Time', value: '4:30pm ET', change: 'Today' },
    ],
  },
  {
    id: 12,
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    filingType: 'DEFA14A',
    filedAt: 'Oct 31, 2025',
    timeAgo: '4 days ago',
    headline: 'Musk deploys X megaphone and employee blast',
    preview: "Employee memo, three Musk X posts, and VoteTesla.com refresh. 9 directors + 2 execs listed as solicitation participants.",
    summaryText: "Tesla unleashed employee memo, three Musk X posts, and VoteTesla.com refresh all on 10/31/2025 to corral votes for 2025 AGM. This DEFA14A flags 9 directors (Elon Musk to Kathleen Wilson-Thompson) and 2 execs (Taneja, Zhu) as solicitation participants.",
    keyTakeaway: "Tesla deploys Musk's X megaphone and employee blast 10/31/2025 to secure AGM votes\u2014watch for opposition signals.",
    investorImpact: "Governance tussle risk if solicitation intensity hints at activist pushback on board or comp.",
    sentiment: 'neutral',
    importance: 'medium',
    icon: Users,
    isStarred: false,
    financialHighlights: [
      { metric: 'Participants', value: '11', change: '9 directors + 2' },
      { metric: 'Channels', value: 'X, Email', change: 'VoteTesla.com' },
      { metric: 'Target', value: 'AGM votes', change: 'Nov 6' },
    ],
  },
  {
    id: 13,
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    filingType: 'Form 4',
    filedAt: 'Oct 31, 2025',
    timeAgo: '4 days ago',
    headline: "Huang sells 25k shares for $5.2M\u20140.003% of holdings",
    preview: "7 tranches at $205-$211. Direct stake now 69.7M shares (~$14.5B), indirect trusts hold 782M more.",
    summaryText: "NVIDIA CEO Jen-Hsun Huang sold 25,000 shares for $5.20M at $207.87/share weighted average on Oct 29\u2014per his Rule 10b5-1 plan from March 20. Direct holdings dipped to 69,733,203 shares (~$14.5B), while indirect trusts hold 782,250,400 more for 852M total (~$177B at sale prices).",
    keyTakeaway: "Huang's 25,000-share trim equals 0.003% of his 852M-share fortress\u2014zero signal on NVDA's trajectory.",
    investorImpact: "Bull thesis untouched: planned micro-sale from CEO with $177B skin in the game screams conviction.",
    sentiment: 'neutral',
    importance: 'low',
    icon: DollarSign,
    isStarred: false,
    financialHighlights: [
      { metric: 'Shares Sold', value: '25,000', change: '0.003%' },
      { metric: 'Proceeds', value: '$5.2M', change: '$207.87 avg' },
      { metric: 'Total Holdings', value: '852M', change: '~$177B' },
    ],
  },
  {
    id: 14,
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    filingType: 'DEFA14A',
    filedAt: 'Nov 3, 2025',
    timeAgo: '5 days ago',
    headline: "Musk demands 25% control for Optimus safety",
    preview: "Ties comp vote to halting robot army if activists boot him. ISS/GL nixed two directors\u2014called 'terrorists'.",
    summaryText: "Tesla's proxy solicitation materials show Musk demanding 25% voting power for Optimus safety, tying comp vote to halting robot army if activists boot him. ISS/Glass Lewis recommended against directors Ira Ehrenpreis and Kathleen Wilson-Thompson, which Musk called 'terrorists' due to inconsistent diversity rules.",
    keyTakeaway: "Nov 6 vote locks in Musk's 25% control or kills Optimus\u2014Elon's red line.",
    investorImpact: "Yes vote secures irreplaceable CEO for AI pivot; no vote torches robot thesis.",
    sentiment: 'bullish',
    importance: 'high',
    icon: AlertTriangle,
    isStarred: false,
    financialHighlights: [
      { metric: 'Voting Target', value: '25%', change: 'From 15%' },
      { metric: 'Stakes', value: 'Optimus', change: 'Robot army' },
      { metric: 'Opposition', value: 'ISS/GL', change: 'No recs' },
    ],
  },
  {
    id: 15,
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    filingType: 'DEFA14A',
    filedAt: 'Oct 29, 2025',
    timeAgo: '5 days ago',
    headline: 'Ad blitz and X posts rally votes for AGM',
    preview: "13 Google ad screenshots, Elon/Kimbal posts attached. Signals contested meeting\u2014likely comp or board fight.",
    summaryText: "Tesla unleashes shareholder letter, 13 Google ad screenshots, and X posts from Elon/Kimbal Musk on Oct 28-29 to rally votes for 2025 annual meeting\u2014no financials, pure proxy push. Nine directors plus Elon, CFO Taneja, SVP Zhu all 'participants' in solicitation.",
    keyTakeaway: "Tesla's ad/social blitz screams contested proxy fight\u2014review DEF14A now or risk missing vote impact.",
    investorImpact: "Hot proxy battle could sway stock on comp ratification or board changes; side with management unless dissidents surface.",
    sentiment: 'neutral',
    importance: 'medium',
    icon: FileText,
    isStarred: false,
    financialHighlights: [
      { metric: 'Materials', value: '13 ads', change: 'Google' },
      { metric: 'Social', value: 'X posts', change: 'Elon/Kimbal' },
      { metric: 'Meeting', value: '2025 AGM', change: 'Contested' },
    ],
  },
];
